[package]
name = "inhibitor"
version = "0.1.0"
edition = "2024"

[dependencies]

[target.'cfg(target_os = "macos")'.dependencies]
objc2-core-foundation = "0.3.2"
objc2-io-kit = "0.3.2"

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_System_Power"] }
