repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: clippy
  - repo: https://github.com/dacci/pre-commit
    rev: v0.2.0
    hooks:
      - id: cargo-test
        args: ['--workspace', '--all-features']
