#!/usr/bin/env bash

set -euo pipefail

main() {
  CARGO_OPTS=(--target aarch64-apple-darwin --target x86_64-apple-darwin)
  PROFILE=debug
  AUTHORITY=""

  while getopts rs: OPT; do
    case $OPT in
      r)
        CARGO_OPTS+=(--release)
        PROFILE=release
        ;;

      s)
        AUTHORITY="$OPTARG"
        ;;

      ?)
        exit -1
        ;;
    esac
  done
  shift $((OPTIND - 1))

  cargo build "${CARGO_OPTS[@]}"

  BUNDLE=target/$PROFILE/Shinobu.app
  rm -rf $BUNDLE

  mkdir -p $BUNDLE/Contents/MacOS
  lipo \
    -create target/*-apple-darwin/$PROFILE/shinobu \
    -output $BUNDLE/Contents/MacOS/shinobu
  cp Info.plist $BUNDLE/Contents

  if [[ -d AppIcon.iconset ]]; then
    mkdir -p $BUNDLE/Contents/Resources
    iconutil \
      -c icns \
      -o $BUNDLE/Contents/Resources/AppIcon.icns \
      AppIcon.iconset
  fi

  if [[ -n "$AUTHORITY" ]]; then
    codesign -s "$AUTHORITY" --timestamp $BUNDLE
  fi
}

[[ ${#BASH_SOURCE[@]} = 1 ]] && main "$@"
