[package]
name = "shinobu"
version = "0.1.0"
edition = "2024"
description = "Shinobu"

[package.metadata.bundle]
name = "Shinobu"
identifier = "org.dacci.shinobu"

[dependencies]
env_logger = { version = "0.11.11", default-features = false, features = ["humantime"] }
libc = "0.2.189"
log = "0.4.33"
objc2 = "0.6.4"
objc2-app-kit = "0.3.2"
objc2-core-foundation = "0.3.2"
objc2-foundation = "0.3.2"
objc2-io-kit = "0.3.2"
objc2-service-management = "0.3.2"
